### ISSUE TITLE
CE notes/questions

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/brain-game#66]
step 4: Regarding translatability, I think it would make sense to have 'no :(' as the negative answer, instead of 'nope :('. I've changed the text in this step 7 and step 2 in line with this, but i can't change the image. Not sure it's essential to swap the image.

step 6: I reformatted the instructions about showing in hiding sprites in response to the backdrop because as it was it wasn't applicable to all sprites. Hope the changes are OK.

step 10: is the 'main menu' the start screen (lines 6 and 9)? Before this step, a menu wasn't mentioned.

**Comment by lawsie** [comment]
Thanks @JaninaPi . I didn't write this one in the first place so some of it is a hangover from other stuff!
Step 4 - Agree, I've changed the image

Step 6 - Added some more as you need to use separate blocks for showing and hiding sprites (purple) to showing and hiding variables (orange) so you might want to check that bit again.

Step 10 - yep, not sure what that's on about, changed it.
